idf_component_register(SRCS "main.c"
                            "config.c"
			    "imu.c"
                            "magnetometer.c"
			    "motor.c"
                            "encoder.c"
                            "speed_controller.c"
                            "uart_interface.c"
                    INCLUDE_DIRS ".")
